# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python build

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: 3.11
      coverage_source:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.version }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ inputs.version }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        shell: bash
      - name: Test and report coverage with pytest
        run: |
          pytest --cov ${{ inputs.coverage_source }}
        shell: bash
